---
- name: Enable CRB repository
  community.general.dnf_config_manager:
    name: crb
  become: true
  register: crb_repository

- name: Install EPEL release
  ansible.builtin.dnf:
    name:
      - epel-release
    state: present
  become: true
  register: epel_release

- name: Install system packages (RPM)
  ansible.builtin.dnf:
    name:
      - tmux
      - jq
      - fd-find
      - gawk
      - perl
      - neovim
      - vim-enhanced
      - vim-minimal
      - gedit
      - git
      - unzip
      - difftastic
      - gh
      - graphviz
      - gcc
      - gcc-c++
      - ninja-build
      - automake
      - autoconf
      - clang
      - golang
      - nodejs
      - python3-devel
      - python3-tomlkit
      - podman
      - helm
      - sqlite-devel
      - libpq-devel
      - libxml2-devel
      - libxslt-devel
      - openssl-devel
      - nss
      - libXrandr
      - libXdamage
      - libXcomposite
      - libxkbcommon-devel
      - libxkbcommon-x11-devel
      - mesa-libgbm
      - libglvnd-gles
      - atk
      - at-spi2-atk
      - alsa-lib
      - dbus-devel
      - dbus-x11
      - systemd-udev
      - systemd-resolved
      - gnome-calculator
      - xdg-utils
      - glibc-langpack-en
      - htop
      - mold
    state: present
  become: true
  when: >
    (not ansible_check_mode)
    or (
      not crb_repository.changed
      and not epel_release.changed
    )
