---
- name: Define authorized SSH keys
  ansible.builtin.set_fact:
    dev_env_authorized_ssh_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJwPHz4woB7Ijlh0vuURsccOn4dUAKIh3dxYjkbl4YFV payton@ibara"
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO8YI8fWC7Lo1ZUDf34OrnBP2VWzqJnWBP1pXMH8M/Y6 leynos@ibara"
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEHXrz+781EJp7TXgPPaRUXFSUOBLdkKUjU1aAAOor0Q leyno@espgaluda"

- name: Create owner user
  ansible.builtin.user:
    name: "{{ owner_user }}"
    state: present
    shell: /bin/bash
    create_home: true

- name: Ensure SSH directories exist
  ansible.builtin.file:
    path: "{{ item.home }}/.ssh"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: '0700'
  loop:
    - name: root
      group: root
      home: /root
    - name: "{{ owner_user }}"
      group: "{{ owner_user }}"
      home: "{{ '/home/' ~ owner_user }}"

- name: Add authorized keys for root and owner user
  ansible.builtin.lineinfile:
    path: "{{ item.0.home }}/.ssh/authorized_keys"
    create: true
    owner: "{{ item.0.name }}"
    group: "{{ item.0.group }}"
    mode: '0600'
    line: "{{ item.1 }}"
  loop: "{{ dev_env_authorized_key_users | product(dev_env_authorized_ssh_keys) }}"
  vars:
    dev_env_authorized_key_users:
      - name: root
        group: root
        home: /root
      - name: "{{ owner_user }}"
        group: "{{ owner_user }}"
        home: "{{ '/home/' ~ owner_user }}"
